# Generated by Django 4.1.3 on 2022-12-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_seller_listing_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(max_length=2000),
        ),
    ]
