# Generated by Django 4.1.3 on 2022-12-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='creator',
            new_name='seller',
        ),
    ]
